### ISSUE TITLE
Implement diffmerge feature

### ISSUE THREAD

**Issue by Hexman768** [Hexman768/Notepad-Sharp#65]
## Description
___
It would be cool to be able to elect to compare the differences between two files. Perhaps we could add it as an option under the menu tool strip.
___
## Preview
___
![Feature_Demo_1](https://user-images.githubusercontent.com/41409007/61841075-13432280-ae59-11e9-9d01-00f5645bdb6e.png)

**Comment by PoLaKoSz** [comment]
I found [libgit2C#](https://github.com/libgit2/libgit2sharp/wiki/git-diff-%7Bfilename%7D---local.patch) which hopefully could do this easily. Should i give it a try?

**Comment by PoLaKoSz** [comment]
Do You work on this because if not i would like to implement it.

**Comment by Hexman768** [comment]
I have not started this issue yet no, you are free to give it a go! Please keep me updated as I would love to see what you come up with!

**Comment by PoLaKoSz** [comment]
My idea would be to put a new submenu called **Diff** into the **View** menu.
When the `Diff` menu clicked it would open a small window which has two TextBox for the two file paths and a Button to start the operation.

- if **Notepad#** has only one open tab (e.g.: **C:\changes.xml**) than the first TextBox's content is **C:\changes.xml** the second one is empty
- If **Notepad#** has exatly two open tabs (e.g.: **C:\changes.xml** and **C:\README.md**) than the first TextBox's content is **C:\changes.xml**, the second one is **C:\README.md**
- If **Notepad#** has more than two open tabs than the two TextBox content would be the first two tabs filepath.

What do You think about this?

**Comment by PoLaKoSz** [comment]
Any comment on this?

**Comment by Hexman768** [comment]
I like the idea. But while your implementing this, keep in mind that this feature or a feature like it may be used for github integration sooner (meaning I might implement the github api in the future to allow users to diff their various commits with the current branch state).

**Comment by Hexman768** [comment]
Just food for thought.

**Comment by Hexman768** [comment]
I also wanted to inform you that I am currently looking for a better syntax highlighter with more features (however the primary reason is simply that this application just doesn't have the best look to it.

**Comment by PoLaKoSz** [comment]
Maybe i should switch to an another issue to prevent working twice or at least needlessly?

**Comment by Hexman768** [comment]
I actually do have a bit of an idea, so for this enhancement, what we could do is this.
I have been working on a complete UI change for Notepad#, and I think it would look good to put the diffmerge feature right next to the current instance of FastColoredTextBox.

**Comment by Hexman768** [comment]
Other than that, the functionality you have recommended seems perfect.

**Comment by PoLaKoSz** [comment]
All right. Hopefully i will be able to implement it tomorrow.

**Comment by Hexman768** [comment]
Sounds good, I am eager to see the implementation!
