### ISSUE TITLE
Current editor language does not change on save

### ISSUE THREAD

**Issue by Hexman768** [Hexman768/Notepad-Sharp#81]
The language attribute of the current editor should change upon a successful save of a file if that file happens to be of a supported language.

**Comment by PoLaKoSz** [comment]
Did You get a notification about i moved this card to the `Done`  column? I hope this is ok.

**Comment by Hexman768** [comment]
Absolutely, I just saw it, thank you! If there are any issues that you would like to take a stab at, I believe you have the permissions to assign issues to yourself so feel free!

**Comment by PoLaKoSz** [comment]
Thank You so much, i want to say it again that this gesture means a lot to me :smiley:
