### ISSUE TITLE
Translation Enhancement

### ISSUE THREAD

**Issue by Hexman768** [Hexman768/Notepad-Sharp#94]
I would like to add a Hungarian translation to this project. The ability to use the program in a different language would be amazing.

**Comment by PoLaKoSz** [comment]
Are You gonna implement a language switcher with only English option first and than i can localize to hungarian, or what is your plan?

**Comment by Hexman768** [comment]
My plan is to do just that. There is some good documentation on the subject here: https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/y99d1cd3(v=vs.100)?redirectedfrom=MSDN

**Comment by Hexman768** [comment]
I will default the program to english (this will be changed down the road but it works for now) and I will provide next steps for you as soon as I am done making sure that everything is ready to go for the actual translation.

**Comment by Hexman768** [comment]
Alright I think I've gotten almost everything ready. When you are ready, checkout my branch and change the language of MainForm to Hungarian. After that, you should be able to click on each item with English text and change it to it's respective Hungarian translation. Once you are done with that, we should be good to go...but I want to test it first just to make sure.

**Comment by PoLaKoSz** [comment]
Added b7e70a205b5311f0067da35a8a6bbb370d542d07 to the branch with the hungarian translation.

**Comment by Hexman768** [comment]
After testing, it doesn't look like the language is actually switching or the text for each component is not updating. We will have to find a fix for this before merging this code change. Once this code change is merged. The other PR (diffmerge) will have to be rebased with changes. Don't worry about it though, I will cherry pick your changes to a branch on this repo and see if I can give you the power to create branches directly from here rather than having to keep a fork synchronized.

**Comment by PoLaKoSz** [comment]
When i wanted to test my work  (b7e70a205b5311f0067da35a8a6bbb370d542d07) i encountered the same issue. After a research i found out that the app needs to be restarted in order to take effect but because the `en-US` is hard coded it will never change the UI so instead it should read it from a config file at startup and when the user want to change it just promp him/her about the required app restart.

If You change the burnt-in `en-US` to `hu-HU` and run the project it should display every text in hungarian.

**Comment by Hexman768** [comment]
You are correct. Not sure why users would want to change the language on-the-fly anyway. I will have to figure out a config system. We will most likely introduce the use of JSON files for the config. These could be stored in the user's appdata directory somewhere just like it does in Notepad++ (at least I'm pretty sure that's where it is).

**Comment by Hexman768** [comment]
For now, I'm going to create a 'blocked' section on the project board and move this issue over there because we will need the config system to be implemented first and we don't want to be stepping on the toes of other issues during the development process.

**Comment by PoLaKoSz** [comment]
All right.

**Comment by PoLaKoSz** [comment]
Blocked by #78 (or at least the back-end required to proceed with this feature).

**Comment by Hexman768** [comment]
Could you test this once again by changing your language localization on your machine to hungarian and then launching the application?

**Comment by PoLaKoSz** [comment]
Of course! But there is a chance that maybe just at the weekend.

**Comment by PoLaKoSz** [comment]
Sorry but even with the last commit the run-time language change is not working.

**Comment by Hexman768** [comment]
I'm not concerned with making it run-time compatible at this point, but if someone were using a pc with   Hungarian language already associated and then started up the application, I just want to make sure that the application is actually in Hungarian

**Comment by Hexman768** [comment]
https://java.com/en/download/help/locale.xml

**Comment by PoLaKoSz** [comment]
Than i am not sure what You wanted to achieve with the last commit.

**Comment by Hexman768** [comment]
I don't either, it will most likely be removed honestly.

**Comment by PoLaKoSz** [comment]
# :smile:

**Comment by Hexman768** [comment]
Were you able to confirm that it works with a Hungarian-localized PC?

**Comment by Hexman768** [comment]
Just an update: we may have to close this branch and start over since their will have been so many changes to the codebase since the branch for this issue was first created.

We will also have to figure out how to get our changes tested.

**Comment by Hexman768** [comment]
I think this issue was and is a good idea, but I do not much like our current implementation so I'm going to close this issue and the branch associated with it. If we decide to do a language enhancement in the future then we can reference this issue for implementation details.
