### ISSUE TITLE
New architecture

### ISSUE THREAD

**Issue by Hexman768** [Hexman768/Notepad-Sharp#96]
For the new architecture, the application will work like this: The MainForm will be nothing more than a collection of controls on a form. The MainForm will also handle events that will be raised from the UserControls that will fire events in order to perform specific functionality from other UserControls. This is to promote loose coupling of UserControls. This also ensures that functionality is actually divided rather than being consolidated to the MainForm.

**Comment by PoLaKoSz** [comment]
I usually use [MvvmCross](https://www.mvvmcross.com/documentation/tutorials/tipcalc/a-wpf-ui-project?scroll=1763) to develop in MVVM style. It has:
- IoC
- ViewModel first aproach
- NavigationService
- ...

**Comment by Hexman768** [comment]
I only chose MVC because it was originally created specifically for desktop applications. I am also the most familiar with it, but I want to look further into this MVVM architecture you have mentioned.

**Comment by PoLaKoSz** [comment]
I found [this](https://www.linkedin.com/pulse/understanding-difference-between-mvc-mvp-mvvm-design-rishabh-software) article but to be honest i never looked up deeply what is the difference between MVC and MVVM i just applied the main goal: separate the layers from each other.

**Comment by Hexman768** [comment]
I have decided to go with the layered architecture. I chose this because MVVM appears to be more for wpf applications rather than traditional winforms apps. The layered structure seems to be pretty simple and easy to get-behind. Here is a link where its explained at a high-level -> https://stackoverflow.com/questions/1324603/architecture-for-winforms-applications

**Comment by Hexman768** [comment]
We will complete this issue before we move on to actually creating the files that will make up the data access layer.

**Comment by Hexman768** [comment]
Here is a technical explanation of some basic operations for a SQLite DB that I will be using when attaching the style configurator to attach to a db.

**Comment by PoLaKoSz** [comment]
Hi!

Can You open a PR for the `feature/architecture` branch because i have some code suggestion?

**Comment by PoLaKoSz** [comment]
Hi!

Can You open a PR with the `feature/architecture` branch, please (i have some code suggestions)?

**Comment by PoLaKoSz** [comment]
Hi!

Can You open a PR with the `feature/architecture` branch, please (i have some suggestions)?

Thank You!

**Comment by Hexman768** [comment]
Sure thing, I do want you to know that it is not quite finished just yet.

**Comment by PoLaKoSz** [comment]
Thank You!

**Comment by Hexman768** [comment]
So I did some more research and it looks like the Mediator pattern is almost exactly what we are looking for. The idea is that a bunch of UserControls are instantiated in the InitializeComponent() function so we can't use constructor injection for the dependencies. This means that we will have to use a mediator class that has access to all controls, each control can raise an event if it needs to talk to another controller. These events are responded to by the mediator class.

**Comment by PoLaKoSz** [comment]
After i read the Mediator pattern on Wikipedia it feels like the Mediator class will become huge over time.

My advice like a few weeks ago the same: use an MVVM framework (can be used in WinForms too) because like i probably mentioned i already use one called MvvmCross and there is a similar class to the Mediator but here this is called `IMvxMessenger `.

Each ViewModel/Controller can register any number and kind of custom event. Just take a quick look at the [documentation](https://www.mvvmcross.com/documentation/plugins/messenger) how simple this is.

**Comment by Hexman768** [comment]
I am going to close this issue as I have found a fantastic solution for our problem here. We will be using [DockPanel Suite](https://github.com/dockpanelsuite/dockpanelsuite) in order to separate the components. Each window should still be able to communicate just fine although I will be updating the theme and overall look of the application. We are getting our first major update! I will go ahead and see if I can make our v1.0 release and then v2.0 will be completed after moving over to DockPanel and working out all of the bugs.
