### ISSUE TITLE
Update FastColoredTextBox

### ISSUE THREAD

**Issue by Hexman768** [Hexman768/Notepad-Sharp#97]
The current version of FastColoredTextBox that we are consuming needs to be updated as there have been a couple new commits since the last time it was updated.

**Comment by Hexman768** [comment]
We may have to change the way that we consume the FastColoredTextBox. I'm not such a big fan of simply consuming the .dll. I'm thinking we could possibly pull it in from NuGet instead. This is the more traditional way of consuming other components.

**Comment by PoLaKoSz** [comment]
The NuGet package is not up-to-date. FCTB could be pulled into the project as a git submodule temporary while the NuGet package won't get updated.
